package jagdx;

public class Z {
   public static int a = 1048576;
   public static int f = 16777216;
   public static int b = 2;
   public static int p = 16;
   public static int i = 32;
   public static int k = 2;
   public static int d = 8192;
   public static int u = 16384;
   public static int x = 65536;
   public static int r = 2;
   public static int q = 8;
   public static int n = 64;
   public static int s = 512;
   public static int z = 33554432;
   public int I;
   public int Z;
   public int C;
   public int B;
   public int D;
   public int F;
   public int J;
   public int S;
   public int A;
   public int E;
   public int G;
   public int H;
   public int K;
   public int L;
   public int M;
   public int N;
   public int O;
   public int P;
   public int Q;
   public int R;
   public int T;
   public int U;
   public int V;
   public int W;
   public int X;
   public int Y;
   public int c;
   public int j;
   public float e;
   public float g;
   public float h;
   public float l;
   public float m;
   public float o;
   public int t;
   public int v;
   public int w;
   public int y;
   public int II;
   public int ZI;
   public int CI;
   public int BI;
   public int DI;
   public int FI;
   public float JI;
   public int SI;
   public int AI;
   public int EI;
   public int GI;
   public int HI;
   public int KI;
   public int LI;
   public float MI;
   public F NI = new F();
   public D OI = new D();
   public int PI;
   public int QI;
   public int RI;
   public int TI;
   public int UI;
   public int VI;
   public int WI;
   public int XI;
   public int YI;
   public int iI;
   public int zI;
   public int cI;
}
